### ISSUE TITLE
need README 

### ISSUE THREAD

**Issue by timercrack** [harveywwu/pyktrader#1]
@harveywwu 你好，本人对这个项目很感兴趣，目前也在做类似的工作，不知您这个项目是私用还是公开的呢？想跟您合作，可否添加一些整体项目架构的介绍和执行流程？

**Comment by harveywwu** [comment]
这个我是想私用，不知道你是什么背景，想做什么。如果可能的话可以一起做

sent by iPhone

**Comment by timercrack** [comment]
目前有一个小团队，在开发一款自动化交易平台，python实现，主要是为了内部开发策略，自营交易使用。可否留个联系方式详谈？本人qq156126289
